### ISSUE TITLE
Tesla Firmware?

### ISSUE THREAD

**Issue by wesbos** [nunojpg/homelink-explorer#1]
Hello - I realize this project is a few years old, but I thought I'd ask if you are aware if this hardware has different firmwares for different auto manufacturers? 

Specifically I'm curious if the exact same hardware from Audi/VW will work on a Tesla, and if there are any methods to flash the hardware if needed.

**Comment by nunojpg** [comment]
Yes, they are different LIN protocol and are not compatible.

**Comment by wesbos** [comment]
gotcha - thank you for your expertise
